/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarPreview: typeof import('./src/components/AvatarPreview/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    ConfigTable: typeof import('./src/components/ConfigTable/index.vue')['default']
    Crontab: typeof import('./src/components/Crontab/index.vue')['default']
    Day: typeof import('./src/components/Crontab/day.vue')['default']
    DictTag: typeof import('./src/components/DictTag/index.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    EnumTag: typeof import('./src/components/EnumTag/index.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload/index.vue')['default']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    HeaderSearch: typeof import('./src/components/HeaderSearch/index.vue')['default']
    Hour: typeof import('./src/components/Crontab/hour.vue')['default']
    IconSelect: typeof import('./src/components/IconSelect/index.vue')['default']
    IFrame: typeof import('./src/components/iFrame/index.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload/index.vue')['default']
    MediaPreview: typeof import('./src/components/MediaPreview/index.vue')['default']
    Min: typeof import('./src/components/Crontab/min.vue')['default']
    Month: typeof import('./src/components/Crontab/month.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    ParentView: typeof import('./src/components/ParentView/index.vue')['default']
    Result: typeof import('./src/components/Crontab/result.vue')['default']
    RightToolbar: typeof import('./src/components/RightToolbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./src/components/Screenfull/index.vue')['default']
    Second: typeof import('./src/components/Crontab/second.vue')['default']
    SizeSelect: typeof import('./src/components/SizeSelect/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TopNav: typeof import('./src/components/TopNav/index.vue')['default']
    Week: typeof import('./src/components/Crontab/week.vue')['default']
    Year: typeof import('./src/components/Crontab/year.vue')['default']
  }
}
