/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDatePicker: typeof import('./../components/AppDatePicker/index.vue')['default']
    AvatarPreview: typeof import('./../components/AvatarPreview/index.vue')['default']
    Breadcrumb: typeof import('./../components/Breadcrumb/index.vue')['default']
    CreatePageShell: typeof import('./../components/CreatePageShell/index.vue')['default']
    Crontab: typeof import('./../components/Crontab/index.vue')['default']
    CrontabDay: typeof import('./../components/Crontab/day.vue')['default']
    CrontabHour: typeof import('./../components/Crontab/hour.vue')['default']
    CrontabMin: typeof import('./../components/Crontab/min.vue')['default']
    CrontabMonth: typeof import('./../components/Crontab/month.vue')['default']
    CrontabResult: typeof import('./../components/Crontab/result.vue')['default']
    CrontabSecond: typeof import('./../components/Crontab/second.vue')['default']
    CrontabWeek: typeof import('./../components/Crontab/week.vue')['default']
    CrontabYear: typeof import('./../components/Crontab/year.vue')['default']
    DictTag: typeof import('./../components/DictTag/index.vue')['default']
    Editor: typeof import('./../components/Editor/index.vue')['default']
    EnumTag: typeof import('./../components/EnumTag/index.vue')['default']
    FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default']
    HeaderSearch: typeof import('./../components/HeaderSearch/index.vue')['default']
    Icon: typeof import('./../components/Icon/index.vue')['default']
    IconSelect: typeof import('./../components/IconSelect/index.vue')['default']
    IFrame: typeof import('./../components/iFrame/index.vue')['default']
    ImageUpload: typeof import('./../components/ImageUpload/index.vue')['default']
    LoadingState: typeof import('./../components/LoadingState/index.vue')['default']
    LocaleSwitcher: typeof import('./../components/LocaleSwitcher/index.vue')['default']
    MediaPreview: typeof import('./../components/MediaPreview/index.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    ParentView: typeof import('./../components/ParentView/index.vue')['default']
    RightToolbar: typeof import('./../components/RightToolbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./../components/Screenfull/index.vue')['default']
    SizeSelect: typeof import('./../components/SizeSelect/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TopNav: typeof import('./../components/TopNav/index.vue')['default']
    VideoAssetPreview: typeof import('./../components/VideoAssetPreview/index.vue')['default']
    VideoAssetPreviewVideoPlayer: typeof import('./../components/VideoAssetPreview/VideoPlayer.vue')['default']
  }
}
